import * as path from 'path'
import type {
  AiImageOutputResolution,
  VisualMixProfile
} from '../../../../shared/types'

/**
 * Manual AI image workflow (Custom Mix -> AI Image Mode = Prompt).
 *
 * In Prompt mode the AI-owned scenes are NOT generated by the app. The app produces a prompt
 * pack, the user creates the images externally and imports them back. These types describe the
 * persisted artifacts (all under <project>/analysis and <project>/assets/generated/manual-ai).
 */

/** Bump when the prompt text recipe changes in a way that must invalidate old prompt packs. */
export const MANUAL_AI_PROMPT_SCHEMA_VERSION = 1
export const MANUAL_AI_MANIFEST_SCHEMA_VERSION = 1

export const MANUAL_AI_SUPPORTED_EXTENSIONS: readonly string[] = ['.png', '.jpg', '.jpeg', '.webp']

export interface ManualAiPromptEntry {
  /** REAL project sceneIndex (never renumbered). */
  sceneIndex: number
  sceneId: string
  /** One physical line, no embedded newlines. */
  prompt: string
  /** Invalidation key: narration + visual intent + profile + prompt + resolution + schema. */
  promptHash: string
  /** Fingerprint of the INPUTS (not the generated text) used to keep prompts stable across runs. */
  inputHash: string
  expectedFilename: string
  status: 'waiting-image'
}

export interface ManualAiPromptPack {
  schemaVersion: number
  generatedAt: string
  profile: VisualMixProfile
  totalProjectScenes: number
  expectedAiImages: number
  imageMode: 'prompt'
  outputResolution: AiImageOutputResolution
  scenes: ManualAiPromptEntry[]
}

export interface ManualAiAssetRecord {
  sceneIndex: number
  promptHash: string
  status: 'ready'
  sourcePath: string
  /** Absolute path of the normalized asset inside assets/generated/manual-ai. */
  localPath: string
  width: number
  height: number
  sourceWidth?: number
  sourceHeight?: number
  importedAt: string
  /** True when the user explicitly chose "Use Anyway" for an image below the quality target. */
  lowResolution?: boolean
  warnings?: string[]
}

export interface ManualAiAssetsManifest {
  schemaVersion: number
  updatedAt: string
  expected: number
  ready: number
  missing: number
  scenes: Record<string, ManualAiAssetRecord>
}

export interface TargetDims {
  width: number
  height: number
}

export function resolutionDims(res?: AiImageOutputResolution): TargetDims {
  if (res === '4k') return { width: 3840, height: 2160 }
  if (res === '2k') return { width: 2560, height: 1440 }
  return { width: 1920, height: 1080 }
}

export function expectedFilenameForScene(sceneIndex: number): string {
  return `S${String(sceneIndex).padStart(4, '0')}.png`
}

export function getManualAiAssetsDir(projectDir: string): string {
  return path.join(projectDir, 'assets', 'generated', 'manual-ai')
}

export function getManualAiPromptJsonPath(projectDir: string): string {
  return path.join(projectDir, 'analysis', 'manual-ai-prompts.json')
}

export function getManualAiPromptTxtPath(projectDir: string): string {
  return path.join(projectDir, 'analysis', 'manual-ai-prompts.txt')
}

export function getManualAiManifestPath(projectDir: string): string {
  return path.join(projectDir, 'analysis', 'manual-ai-assets.json')
}

export function getVisualMixPlanFilePath(projectDir: string): string {
  return path.join(projectDir, 'analysis', 'visual-mix-plan.json')
}
