import * as path from 'path'
import type {
  AiImageOutputResolution,
  VisualMixProfile
} from '../../../../shared/types'

/**
 * Manual AI image workflow (Custom Mix -> AI Image Mode = Prompt).
 *
 * In Prompt mode the AI-owned scenes are NOT generated by the app. The app produces a prompt
 * pack, the user creates the images externally and imports them back. These types describe the
 * persisted artifacts (all under <project>/analysis and <project>/assets/generated/manual-ai).
 */

/** Bump when the prompt text recipe changes in a way that must invalidate old prompt packs. */
export const MANUAL_AI_PROMPT_SCHEMA_VERSION = 1
export const MANUAL_AI_MANIFEST_SCHEMA_VERSION = 1

export const MANUAL_AI_SUPPORTED_EXTENSIONS: readonly string[] = ['.png', '.jpg', '.jpeg', '.webp']

export const MANUAL_AI_VISUAL_DIRECTOR_SCHEMA_VERSION = 1

export type ManualAiStorytellingMode =
  | 'mechanism-explainer'
  | 'investigative'
  | 'warning'
  | 'myth-busting'
  | 'comparison'
  | 'problem-solution'
  | 'historical-narrative'
  | 'financial-explainer'
  | 'lifestyle-explainer'
  | 'scientific-explainer'
  | 'documentary'
  | 'other'

export interface ManualAiVisualBrief {
  schemaVersion: number
  generatedAt: string
  scriptHash: string
  profile: 'health' | 'general'
  primaryNiche: string
  secondaryNiches: string[]
  storytellingMode: ManualAiStorytellingMode
  corePromise: string
  centralQuestion: string
  centralThesis: string
  audienceTakeaway: string
  emotionalArc: string[]
  narrativeArc: Array<{
    phase: string
    purpose: string
  }>
  visualStrategy: {
    dominantStyle: string
    realismLevel: string
    cameraLanguage: string
    lightingLanguage: string
    colorLanguage: string
    depthLanguage: string
    recurringMotifs: string[]
    avoidVisualCliches: string[]
  }
  hookStrategy: {
    primaryHookType: string
    tensionSources: string[]
    curiosityPatterns: string[]
  }
  overlayStrategy: {
    enabled: boolean
    targetDensity: number
    maxDensity: number
    maxWords: number
    maxCharacters: number
    avoidBottomCaptionArea: boolean
  }
  modelUsed: string
  fallbackUsed: boolean
}

export type ManualAiSceneRole =
  | 'hook'
  | 'question'
  | 'problem'
  | 'symptom'
  | 'setup'
  | 'mechanism'
  | 'cause-effect'
  | 'reveal'
  | 'evidence'
  | 'statistic'
  | 'comparison'
  | 'definition'
  | 'demonstration'
  | 'consequence'
  | 'solution'
  | 'lifestyle'
  | 'emotion'
  | 'transition'
  | 'recap'

export type ManualAiHookLevel = 'low' | 'medium' | 'high'

export interface ManualAiSceneDirection {
  sceneIndex: number
  sceneRole: ManualAiSceneRole
  hookLevel: ManualAiHookLevel
  coreMeaning: string
  viewerShouldNotice: string
  curiosityGap?: string
  visualEvent: {
    subject: string
    action: string
    change?: string
    cause?: string
    consequence?: string
  }
  composition: {
    shotType: string
    cameraAngle: string
    lensFeel: string
    focalPriority: string
    foreground: string
    background: string
    negativeSpace?: string
  }
  lighting: string
  colorStrategy: string
  continuityNote?: string
  textOverlay: {
    enabled: boolean
    text?: string
    purpose?:
      | 'hook'
      | 'mechanism'
      | 'stat'
      | 'comparison'
      | 'term'
      | 'reveal'
      | 'conclusion'
    position?:
      | 'top-left'
      | 'top-right'
      | 'center-left'
      | 'center-right'
    emphasis?:
      | 'medium'
      | 'high'
    reason: string
  }
  avoid: string[]
  confidence: number
}

export interface ManualAiSceneDirectionsArtifact {
  schemaVersion: number
  generatedAt: string
  briefHash: string
  inputHash: string
  totalAiScenes: number
  enrichedCount: number
  fallbackCount: number
  overlayCount: number
  directions: ManualAiSceneDirection[]
}

export interface ManualAiPromptEntry {
  /** REAL project sceneIndex (never renumbered). */
  sceneIndex: number
  sceneId: string
  /** One physical line, no embedded newlines. */
  prompt: string
  /** Invalidation key: narration + visual intent + profile + prompt + resolution + schema. */
  promptHash: string
  /** Fingerprint of the INPUTS (not the generated text) used to keep prompts stable across runs. */
  inputHash: string
  expectedFilename: string
  status: 'waiting-image'

  /** Optional Visual Director metadata (backward compatible) */
  sceneRole?: ManualAiSceneRole
  hookLevel?: ManualAiHookLevel
  visualEvent?: {
    subject: string
    action: string
    change?: string
    consequence?: string
  }
  textOverlay?: {
    enabled: boolean
    text?: string
    purpose?: string
    position?: string
    emphasis?: string
    reason?: string
  }
  directorSource?: 'ai' | 'fallback'
  directorConfidence?: number
  qualityScore?: number
}

export interface ManualAiPromptPack {
  schemaVersion: number
  generatedAt: string
  profile: VisualMixProfile
  totalProjectScenes: number
  expectedAiImages: number
  imageMode: 'prompt'
  outputResolution: AiImageOutputResolution
  scenes: ManualAiPromptEntry[]
}

export interface ManualAiAssetRecord {
  sceneIndex: number
  promptHash: string
  status: 'ready'
  sourcePath: string
  /** Absolute path of the normalized asset inside assets/generated/manual-ai. */
  localPath: string
  width: number
  height: number
  sourceWidth?: number
  sourceHeight?: number
  importedAt: string
  /** True when the user explicitly chose "Use Anyway" for an image below the quality target. */
  lowResolution?: boolean
  warnings?: string[]
}

export interface ManualAiAssetsManifest {
  schemaVersion: number
  updatedAt: string
  expected: number
  ready: number
  missing: number
  scenes: Record<string, ManualAiAssetRecord>
}

export interface TargetDims {
  width: number
  height: number
}

export function resolutionDims(res?: AiImageOutputResolution): TargetDims {
  if (res === '4k') return { width: 3840, height: 2160 }
  if (res === '2k') return { width: 2560, height: 1440 }
  return { width: 1920, height: 1080 }
}

export function expectedFilenameForScene(sceneIndex: number): string {
  return `S${String(sceneIndex).padStart(4, '0')}.png`
}

export function getManualAiAssetsDir(projectDir: string): string {
  return path.join(projectDir, 'assets', 'generated', 'manual-ai')
}

export function getManualAiPromptJsonPath(projectDir: string): string {
  return path.join(projectDir, 'analysis', 'manual-ai-prompts.json')
}

export function getManualAiPromptTxtPath(projectDir: string): string {
  return path.join(projectDir, 'analysis', 'manual-ai-prompts.txt')
}

export function getManualAiVisualBriefPath(projectDir: string): string {
  return path.join(projectDir, 'analysis', 'manual-ai-visual-brief.json')
}

export function getManualAiSceneDirectionsPath(projectDir: string): string {
  return path.join(projectDir, 'analysis', 'manual-ai-scene-directions.json')
}

export function getManualAiManifestPath(projectDir: string): string {
  return path.join(projectDir, 'analysis', 'manual-ai-assets.json')
}

export function getVisualMixPlanFilePath(projectDir: string): string {
  return path.join(projectDir, 'analysis', 'visual-mix-plan.json')
}
